services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.2.1
    volumes:
      - /home/kletson/appdata/uptimekuma/data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - 3001:3001
    restart: on-failure:3
    mem_limit: 512m
    memswap_limit: 512m
